targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          exclude:                # <─ easier to read than a negated glob
            - lib/**/objectbox.dart
            - lib/**/objectbox.g.dart
