name: gym_genius
description: "App for tracking workouts."
publish_to: 'none'
version: 0.1.12

environment:
  sdk: ^3.6.0

dependencies:
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0
  equatable: ^2.0.7
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  http: ^1.4.0
  json_annotation: ^4.9.0
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.3.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.5
  objectbox_generator: ^4.3.0
  sqflite_common_ffi: ^2.3.5
  very_good_analysis: ^9.0.0

objectbox:
  output_dir: core/data/datasources/local

flutter:
  uses-material-design: true
  assets:
    - assets/exercise_pictures/
    - assets/exercises.json
    - assets/apple_ai.png
  fonts:
    - family: Montserrat
      fonts:
      - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
      - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
        style: italic
