name: Mobile CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        default: 'prod'

  push:
    branches:
      - main
    paths:
      - 'mobile/**'

  pull_request:
    branches:
      - main
    paths:
      - 'mobile/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
#    needs: lint
    environment:
      name: prod
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/gym-genius/
            git pull
            docker compose up -d --force-recreate --build mobile